In [2]:
import os
import json
import pandas as pd

from datetime import datetime
from utils.config import DRLConfig
from utils.drl_train import training_pipeline

%load_ext autoreload
%autoreload 2

In [3]:
df_ret = pd.read_parquet("../data/returns.parquet")
df_prices = pd.read_parquet("../data/prices.parquet")
df_vol = pd.read_parquet("../data/vola.parquet")

In [67]:
# create portfolio env
from utils.portfolio_env import PortfolioEnv
env = PortfolioEnv(df_ret, df_prices, df_vol)
print(env.portfolio)
env.portfolio.print_summary()
display(env.portfolio.get_history())

Portfolio with 11 assets, initial value: $100,000.00, current value: $100,000.00

=== Current State ===
Initial Balance: $100,000.00
Portfolio Value: $100,000.00
Cash: $100,000.00
Cash Weight: 100.00%

Current Holdings:
No current holdings

=== History & Configuration ===
Number of Records: 0

Assets:
  - XLF
  - XLK
  - XLV
  - XLY
  - XLP
  - XLE
  - XLI
  - XLU
  - XLB
  - XLRE
  - XLC
No history found

Empty DataFrame
Columns: []
Index: []

In [68]:
# sample random action
action = env.action_space.sample()
print(action)

# update env
env.step(action)

# check portfolio object in portfolio env
print(env.portfolio)
env.portfolio.print_summary()
display(env.portfolio.get_history())

[0.8326831  0.26276296 0.1494625  0.37552872 0.8933227  0.86001146
 0.06052167 0.6100079  0.02273275 0.27087596 0.45882887]
Portfolio with 11 assets, initial value: $100,000.00, current value: $100,000.00

=== Current State ===
Initial Balance: $100,000.00
Portfolio Value: $100,000.00
Cash: $16,302.35
Cash Weight: 16.30%

Current Holdings:
| Asset   |   Shares | Weight   | Value       |
|:--------|---------:|:---------|:------------|
| XLI     |      288 | 5.95%    | $ 5,950.63  |
| XLU     |      709 | 10.31%   | $ 10,309.11 |
| XLB     |      295 | 5.72%    | $ 5,723.25  |
| XLE     |      545 | 13.24%   | $ 13,243.40 |
| XLV     |      305 | 6.49%    | $ 6,491.29  |
| XLY     |      316 | 8.14%    | $ 8,135.75  |
| XLP     |     1001 | 13.69%   | $ 13,690.63 |
| XLK     |      483 | 7.28%    | $ 7,281.20  |
| XLF     |      837 | 12.87%   | $ 12,872.39 |

=== Performance Metrics ===
| Metrics   | Value   |
|-----------|---------|

=== History & Configuration ===
Number of Records: 1
Date Range: 2005-03-31 00:00:00 to 2005-03-31 00:00:00

Assets:
  - XLF
  - XLK
  - XLV
  - XLY
  - XLP
  - XLE
  - XLI
  - XLU
  - XLB
  - XLRE
  - XLC

,portfolio_value,cash,w_c,w_XLF,w_XLK,w_XLV,w_XLY,w_XLP,w_XLE,w_XLI,...,s_XLK,s_XLV,s_XLY,s_XLP,s_XLE,s_XLI,s_XLU,s_XLB,s_XLRE,s_XLC
date,,,,,,,,,,,,,,,,,,,,,
2005-03-31,100000.0,16302.345749,0.163023,0.1287,0.0728,0.0649,0.0814,0.1369,0.1324,0.0595,...,483,305,316,1001,545,288,709,295,0,0