In [1]:
import pandas as pd
from backtest.backtester import MVOBacktester

In [2]:
%load_ext autoreload
%autoreload 2

In [30]:
# Load data
returns = pd.read_parquet("./data/returns.parquet")
prices = pd.read_parquet("./data/prices.parquet")
tickers = returns.columns.tolist()

In [39]:
# Run backtest
my_backtester = MVOBacktester(returns, prices, tickers)
results_df = my_backtester.run("2017-01-01", "2019-01-10")

Date 2017-01-02 00:00:00 not in returns or prices
Date 2017-01-16 00:00:00 not in returns or prices
Date 2017-02-20 00:00:00 not in returns or prices
Date 2017-04-14 00:00:00 not in returns or prices
Date 2017-05-29 00:00:00 not in returns or prices
Date 2017-07-04 00:00:00 not in returns or prices
Date 2017-09-04 00:00:00 not in returns or prices
Date 2017-11-23 00:00:00 not in returns or prices
Date 2017-12-25 00:00:00 not in returns or prices
Date 2018-01-01 00:00:00 not in returns or prices
Date 2018-01-15 00:00:00 not in returns or prices
Date 2018-02-19 00:00:00 not in returns or prices
Date 2018-03-30 00:00:00 not in returns or prices
No valid weights found for date 2018-04-03 00:00:00
No valid weights found for date 2018-04-04 00:00:00
No valid weights found for date 2018-04-09 00:00:00
No valid weights found for date 2018-04-11 00:00:00
No valid weights found for date 2018-04-16 00:00:00
No valid weights found for date 2018-04-24 00:00:00
Date 2018-05-28 00:00:00 not in returns or prices
Date 2018-07-04 00:00:00 not in returns or prices
Date 2018-09-03 00:00:00 not in returns or prices
Date 2018-11-22 00:00:00 not in returns or prices
Date 2018-12-05 00:00:00 not in returns or prices
Date 2018-12-25 00:00:00 not in returns or prices
Date 2019-01-01 00:00:00 not in returns or prices
No valid weights found for date 2019-01-03 00:00:00
No valid weights found for date 2019-01-04 00:00:00
No valid weights found for date 2019-01-07 00:00:00
No valid weights found for date 2019-01-08 00:00:00

In [41]:
# Inspect or plot
display(results_df.tail())

,portfolio_value,cash,XLF_shares,XLK_shares,XLV_shares,XLY_shares,XLP_shares,XLE_shares,XLI_shares,XLU_shares,XLB_shares,XLRE_shares,XLC_shares
date,,,,,,,,,,,,,
2018-12-28,103101.226204,215.877224,448.0,162.0,122.0,101.0,218.0,220.0,163.0,216.0,212.0,372.0,240.0
2018-12-31,103827.060539,216.068638,447.0,161.0,121.0,101.0,219.0,220.0,162.0,217.0,212.0,374.0,242.0
2019-01-02,103814.784433,208.200928,443.0,161.0,123.0,100.0,220.0,216.0,162.0,221.0,211.0,382.0,238.0
2019-01-09,107195.299282,236.562037,450.0,163.0,124.0,98.0,224.0,210.0,161.0,225.0,212.0,381.0,233.0
2019-01-10,107838.597929,284.078403,453.0,163.0,124.0,99.0,224.0,210.0,160.0,223.0,212.0,377.0,234.0